### ISSUE TITLE
exportdir: path not found

### ISSUE THREAD

**Issue by mmokrejs** [nlitsme/extfstools#20]
Hi,
  would it be possible to improve the error message so taht the path is shown? I used the a838c9b49113ecaa41a74938c43e423e3a01c897 commit version.

  It feels that `some_dir/:'pwd'` is wrong and `some_dir/:.` too.

```
# ext2rd raw_ext4_image.bin some_dir/:'pwd' 
ehmagic=080e -  0e 08 00 00 00 00 00 00 1c 00 00 00
exportdir: path not found
#
```

Are you aware of https://sourceforge.net/p/ext4magic/tickets/ being unmaintained and that its re-write [ext4magic](https://ext4magic.sourceforge.net/ext4magic_en.html) also has issues? I think helping these could be more helpful to the people. :-)

**Comment by nlitsme** [comment]
I added the path to the error message.  It will be exactly the  path you specify, so it should not be hard to see which one fails.

About using  `'pwd'`  with a single quote: don't you mean to use a backtick?

About the other tools: I currently don't have an interest in maintaining other tools.

Also,  I myself no longer use ext2rd, since it is does not support ext4.  I mostly wrote and used this tool when my development PC was a windows PC, and later a mac, and android still used ext2 or ext3.

I found  https://libguestfs.org/guestfish.1.html  quite useful when I need to inspect a filesystem and don't want to actually mount it.
